language: ruby
cache: bundler
rvm:
  - 2.7.1
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --jobs=3 --retry=3
script:
  - bundle exec jekyll clean && bundle exec jekyll build
branches:
  only:
    - developement
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _site/
  target_branch: master
  on:
    branch: developement

